#!/bin/bash
version=3.11.0

# get source code
git clone https://gitlab.com/ase/ase.git .
git checkout $version

# load build environment
module swap PrgEnv-cray PrgEnv-gnu

# set target directory
tgt=/appl/nano/ase/$version

# install and fix dirs
python setup.py install --prefix=$tgt 2>&1 | tee loki-inst
mv -i $tgt/lib64 $tgt/lib
mv -i $tgt/lib/python2.6/site-packages $tgt/lib/python
rmdir $tgt/lib/python2.6

# fix permissions
chmod -R g+rwX $tgt
chmod -R o+rX $tgt

